ahoyapi: v2
usage: DKAN cli app for development using ahoy.
commands:
  docker:
    usage: A series of docker commands (experimental)
    imports:
      - .ahoy/docker.ahoy.yml
  api:
    usage:
    imports:
      - .ahoy/api.ahoy.yml
